[build] 
command = "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
environment = { 
    PYTHON_VERSION = "3.8"  # Specify the Python version you need, if you use a `.python-version` file, this may not be necessary.
  }