# Generated by Django 3.0.2 on 2025-01-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_auto_20250105_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingguest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
