# Generated by Django 3.0.2 on 2025-02-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_weddingguest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingguest',
            name='is_rsvped',
            field=models.BooleanField(default=False),
        ),
    ]
