# Generated by Django 3.0.2 on 2025-02-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0006_weddingguest_is_rsvped'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingguest',
            name='is_plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
