# Generated by Django 3.0.2 on 2025-02-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0007_weddingguest_is_plus_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingguest',
            name='is_plus_one',
        ),
    ]
