# Generated by Django 3.0.2 on 2025-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0008_remove_weddingguest_is_plus_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingguest',
            name='password',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
