# Generated by Django 3.0.2 on 2025-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_weddingguest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingguest',
            name='password',
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='staying_at_hotel',
            field=models.BooleanField(default=False),
        ),
    ]
